services: 
  banking-microservice: 
    image: tomcat:8.5
    build: 
      context: .
    ports: 
      - "8000:8080"  # Map port 8080 of the container to port 8080 on the host 
    networks: 
      - banking-network
    volumes: 
      - ./target/mvn-hello-world.war:/usr/local/tomcat/webapps/ROOT.war

networks: 
  banking-network: 
    driver: bridge
