version: '3.8' 

 
services: 

  banking-microservice: 

    image: banking-microservice:1.0 

    ports: 

      - "8000:8080"  # Map port 8080 of the container to port 8080 on the host 

    networks: 

      - banking-network 

    volumes: 

      - ./target/mvn-hello-world.war:/usr/local/tomcat/webapps/mvn-hello-world.war
 

networks: 

  banking-network: 

    driver: bridge 

 
