---
- name: Install Ansible
  hosts: host1
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - software-properties-common
          - python3-apt
        state: present
    - name: Add Ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
    - name: Update apt cache
      apt: update_cache=yes
    - name: Install Ansible
      apt:
        name: ansible
        state: present
